spectaql:
    #logoFile: ./test/fixtures/logo.png
    #faviconFile: ./test/fixtures/favicon.png
    displayAllServers: true
    targetDir: documentation/graphql/

introspection:
    removeTrailingPeriodFromDescriptions: false
    #schemaFile: ./examples/data/schema.gql
    #metadataFile: ./examples/data/metadata.json
    url: http://localhost:3000/graphql
    d#ynamicExamplesProcessingModule: ./examples/customizations/examples
    queryNameStrategy: capitalizeFirst
    fieldExpansionDepth: 2

    spectaqlDirective:
        enable: true

extensions:
    graphqlScalarExamples: true

info:
    title: AIP GraphQL Service documentaton
    description: Up to date documentation of the AIP GQL schema
    contact:
        name: API Support
        url: http://www.example.com/support
        email: support@example.com
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
    x-introItems:
        - title: Getting started
          description: Some important stuff we wanted you to know. Supports `markdown`

servers:
    - url: http://localhost:3000/graphql
      description: Local
      # production: true
      headers:
          - name: Authorization
            example: Bearer <TOKEN>
            comment: Required for all calls.
