import { GisibUnit } from '../types/GisibUnit';

export const gisibUnit: GisibUnit[] = [
	{
		type: 'Feature',
		geometry: {
			type: 'Polygon',
			crs: null,
			coordinates: [[[]]],
		},
		properties: {
			'NEN Element': {
				Id: 653079,
				GUID: '{BF277C32-24B0-4350-BF04-7B30DC1C809B}',
				Url: '/api/Collections/NEN Element/items/653079',
				Description: null,
			},
			Hoeveelheid: null,
			Specificatie: null,
			'Jaar van aanleg': null,
			'Jaar uitgevoerd onderhoud': null,
			'Jaar laatste conservering': null,
			Kleur: null,
			'BGT Bronhouder': null,
			'BGT Eindregistratie': null,
			'BGT Type': null,
			'BGT In onderzoek': null,
			'BGT Objecttype': null,
			'BGT Opmerking': null,
			'BGT Status': null,
			'ID uit oude beheerindeling': '688876',
			Identificatie: null,
			'LV publicatiedatum': null,
			'Relatieve hoogteligging': null,
			'Tijdstip registratie': null,
			Beweegbaar: null,
			'Hoort bij type overbrugging': null,
			'Type overbruggingsdeel': null,
			'NEN Type bouwdeel': {
				Id: 3133,
				GUID: '{631C6860-77AC-4964-A968-88D13BAF3A27}',
				Url: '/api/Collections/NEN Type bouwdeel/items/3133',
				Description: 'Leuning',
			},
			'NEN Conditiescore opname': null,
			'NEN Conditiescore opname_DATE': null,
			'NEN Verzorgingsscore opname': null,
			'NEN Verzorgingsscore opname_DATE': null,
			Conservering: null,
			Ingrijpmoment: null,
			Kunstwerkpositionering: null,
			Kwaliteitsnota: null,
			Levensduur: null,
			Memo: null,
			'NEN Conditiescore berekend': null,
			'NEN Conditiescore vastgesteld': null,
			'NEN Eenheid': null,
			'NEN Vakdiscipline': {
				Id: 3264,
				GUID: '{8D340D4C-57A3-4165-B018-E50E8465B67F}',
				Url: '/api/Collections/NEN Vakdiscipline/items/3264',
				Description: 'Kunstwerken',
			},
			'NEN Verzorgingsscore vastgesteld': null,
			Onderhoudsstrategie: null,
			'Reserveonderdeel aanwezig': false,
			Risiconiveau: null,
			Risicowaarde: null,
			'Totale hoeveelheid': null,
			Vervangingsfactor: null,
			Vervangingsjaar: null,
			'Vervangingsjaar recent': null,
			Vervangingswaarde: null,
			'Aangemaakt door': 'Devente-Prins, Ellen',
			'IMGeo Plusstatus': null,
			'BOR Type': null,
			'IMGeo Plustype': null,
			Eenheid: null,
			Deelsportcomplex: null,
			Inwinningsbedrijf: null,
			Sportterrein: null,
			Sportveld: null,
			Discipline: null,
			Locatieaanduiding: null,
			'TAG Nummer': null,
			Sectie: null,
			Revisietekeningnummer: null,
			Fabrikant: null,
			Model: null,
			Installateur: null,
			Installatiedatum: null,
			'Datum tekening gewijzigd': null,
			Serienummer: null,
			'NEN Materiaalsoort': {
				Id: 3165,
				GUID: '{1079DC19-DFC5-45A7-B8CB-478AF3B9BCB7}',
				Url: '/api/Collections/NEN Materiaalsoort/items/3165',
				Description: 'Staal',
			},
			'Civiele constructie': {
				Id: 651491,
				GUID: '',
				Url: '/api/Collections/Civiele constructie/items/651491',
				Description: null,
			},
			Code: 'BRU0353-414-1-2192-1',
			GUID: '{244EE642-A869-49C8-B1AF-BC8F84B70139}',
			Id: 669700,
			Description: null,
			IMGeoId: null,
			Valid_Till: null,
			LastUpdate: '2019-12-06T13:32:54',
			Revisie: 1,
		},
	},
	{
		type: 'Feature',
		geometry: {
			type: 'Polygon',
			crs: null,
			coordinates: [[[]]],
		},
		properties: {
			'NEN Element': {
				Id: 653079,
				GUID: '{BF277C32-24B0-4350-BF04-7B30DC1C809B}',
				Url: '/api/Collections/NEN Element/items/653079',
				Description: null,
			},
			Hoeveelheid: null,
			Specificatie: null,
			'Jaar van aanleg': null,
			'Jaar uitgevoerd onderhoud': null,
			'Jaar laatste conservering': null,
			Kleur: null,
			'BGT Bronhouder': null,
			'BGT Eindregistratie': null,
			'BGT Type': null,
			'BGT In onderzoek': null,
			'BGT Objecttype': null,
			'BGT Opmerking': null,
			'BGT Status': null,
			'ID uit oude beheerindeling': '688875',
			Identificatie: null,
			'LV publicatiedatum': null,
			'Relatieve hoogteligging': null,
			'Tijdstip registratie': null,
			Beweegbaar: null,
			'Hoort bij type overbrugging': null,
			'Type overbruggingsdeel': null,
			'NEN Type bouwdeel': {
				Id: 3090,
				GUID: '{4576DD4A-25C7-485D-9E0A-3938629955DC}',
				Url: '/api/Collections/NEN Type bouwdeel/items/3090',
				Description: 'Leuningafwerking',
			},
			'NEN Conditiescore opname': null,
			'NEN Conditiescore opname_DATE': null,
			'NEN Verzorgingsscore opname': null,
			'NEN Verzorgingsscore opname_DATE': null,
			Conservering: null,
			Ingrijpmoment: null,
			Kunstwerkpositionering: null,
			Kwaliteitsnota: null,
			Levensduur: null,
			Memo: null,
			'NEN Conditiescore berekend': null,
			'NEN Conditiescore vastgesteld': null,
			'NEN Eenheid': null,
			'NEN Vakdiscipline': {
				Id: 3264,
				GUID: '{8D340D4C-57A3-4165-B018-E50E8465B67F}',
				Url: '/api/Collections/NEN Vakdiscipline/items/3264',
				Description: 'Kunstwerken',
			},
			'NEN Verzorgingsscore vastgesteld': null,
			Onderhoudsstrategie: null,
			'Reserveonderdeel aanwezig': false,
			Risiconiveau: null,
			Risicowaarde: null,
			'Totale hoeveelheid': null,
			Vervangingsfactor: null,
			Vervangingsjaar: null,
			'Vervangingsjaar recent': null,
			Vervangingswaarde: null,
			'Aangemaakt door': 'Devente-Prins, Ellen',
			'IMGeo Plusstatus': null,
			'BOR Type': null,
			'IMGeo Plustype': null,
			Eenheid: null,
			Deelsportcomplex: null,
			Inwinningsbedrijf: null,
			Sportterrein: null,
			Sportveld: null,
			Discipline: null,
			Locatieaanduiding: null,
			'TAG Nummer': null,
			Sectie: null,
			Revisietekeningnummer: null,
			Fabrikant: null,
			Model: null,
			Installateur: null,
			Installatiedatum: null,
			'Datum tekening gewijzigd': null,
			Serienummer: null,
			'NEN Materiaalsoort': {
				Id: 3158,
				GUID: '{37362606-CFFD-47B6-B79D-8C19FAEE9E96}',
				Url: '/api/Collections/NEN Materiaalsoort/items/3158',
				Description: 'Kunststof',
			},
			'Civiele constructie': {
				Id: 651491,
				GUID: '',
				Url: '/api/Collections/Civiele constructie/items/651491',
				Description: null,
			},
			Code: 'BRU0353-414-1-2145-1',
			GUID: '{708FB702-E7C5-4BE2-B9CD-42DEBFB0B8A4}',
			Id: 669699,
			Description: null,
			IMGeoId: null,
			Valid_Till: null,
			LastUpdate: '2019-12-06T13:32:54',
			Revisie: 1,
		},
	},
];
