import { GisibAsset } from '../types/GisibAsset';
import { GisibFeature } from '../types/GisibFeature';

export const gisibAsset: GisibFeature<GisibAsset> = {
	type: 'Feature',
	geometry: {
		type: 'Polygon',
		crs: null,
		coordinates: [[[]]],
	},
	properties: {
		GUID: '{4607462D-D5DB-421E-90D7-152CA0282095}',
		'NEN Conditiescore opname': null,
		'NEN Conditiescore opname_DATE': null,
		'NEN Verzorgingsscore opname': null,
		'NEN Verzorgingsscore opname_DATE': null,
		'Type gedetailleerd': null,
		'Aangemaakt door': null,
		Aanleghoogte: null,
		Beheerder: null,
		'Beheerder gedetailleerd': null,
		Beheergebied: null,
		'Beschermde flora en fauna': null,
		'BGT Bronhouder': null,
		'BGT Eindregistratie': null,
		'BGT In onderzoek': null,
		'BGT Objecttype': null,
		'BGT Opmerking': null,
		'BGT Status': null,
		Breedte: null,
		Eigenaar: null,
		'Eigenaar gedetailleerd': null,
		Gebiedstype: null,
		Gebruiksfunctie: null,
		Gemeente: null,
		Grondsoort: null,
		Hoogte: null,
		'ID uit oude beheerindeling': null,
		Identificatie: null,
		'IMGeo Plusstatus': null,
		'Jaar uitgevoerd onderhoud': null,
		'Jaar van aanleg': null,
		Lengte: null,
		Leverancier: null,
		Ligging: null,
		'LV publicatiedatum': null,
		Materiaal: null,
		Memo: null,
		MSLINK: null,
		Objecttype: null,
		Onderhoudsplichtige: null,
		'Openbare ruimte': null,
		Opleverdatum: null,
		Oppervlakte: null,
		'Relatieve hoogteligging': null,
		'Theoretisch eindjaar': null,
		'Tijdstip registratie': null,
		Type: null,
		Verwijderdatum: null,
		Waterschap: null,
		Wijk: null,
		'Wijze van inwinning': null,
		Woonplaats: null,
		Zettingsgevoeligheid: null,
		Objectnaam: null,
		Objectnummer: 'BRU5032',
		'NEN Type beheerobject': null,
		Postcode: null,
		'Stadsdeel of kern': null,
		'Zettingsgevoeligheid gedetailleerd': null,
		Buurt: null,
		'Grondsoort gedetailleerd': null,
		'Datum inwinning': null,
		Vervangingsjaar: null,
		Code: null,
		Vervangingswaarde: null,
		Wegnummer: null,
		'Actueel kwaliteitsniveau': null,
		'BGT Type': null,
		Fabrikant: null,
		Fundering: null,
		'Gewenst kwaliteitsniveau': null,
		'IMGeo Plustype': null,
		Installateur: null,
		Kleur: null,
		Locatieaanduiding: null,
		'Type onderdeel': null,
		'BOR Type': null,
		Conditiescore: null,
		Beheerafspraak: {
			Id: 3399977,
			GUID: '{099EAFE3-B067-40F8-BA09-0AFBAE0AB535}',
			Url: '/api/Collections/Beheerafspraak/items/3399977',
			Description: 'Civiel - Weesp',
		},
		Deelsportcomplex: null,
		Inwinningsbedrijf: null,
		Sportterrein: null,
		Sportveld: null,
		Rangvolgorde: null,
		Id: 3399979,
		Description: null,
		IMGeoId: null,
		Valid_Till: null,
		LastUpdate: '2022-02-14T16:25:04.906059',
		Revisie: 1,
	},
};
