import { GisibElement } from '../types/GisibElement';
import { GisibFeature } from '../types/GisibFeature';

export const gisibElement1: GisibFeature<GisibElement> = {
	type: 'Feature',
	geometry: {
		type: '',
		crs: null,
		coordinates: [[[]]],
	},
	properties: {
		'NEN Type element': {
			Id: 2112,
			GUID: '{19341A39-233F-41D8-B289-9DBFFE91C4E9}',
			Url: '/api/Collections/NEN Type element/items/2112',
			Description: 'Binnenverlichting',
		},
		Hoeveelheid: null,
		Eenheid: null,
		Specificatie: null,
		'NEN Conditiescore opname': null,
		'NEN Conditiescore opname_DATE': null,
		'NEN Verzorgingsscore opname': null,
		'NEN Verzorgingsscore opname_DATE': null,
		'Civiele constructie': {
			Id: 651385,
			GUID: '',
			Url: '/api/Collections/Civiele constructie/items/651385',
			Description: null,
		},
		'NEN Code': null,
		'Type sluisdeur': null,
		'Aangemaakt door': 'Reitsma, Tjitse',
		Aanleghoogte: null,
		'Anti graffiti voorziening': null,
		'Begin garantieperiode': null,
		Bouwjaar: null,
		Breedte: null,
		'Breedte nivelleerschijf': null,
		Deurnummer: null,
		Deursetnummer: null,
		Diepte: null,
		Dikte: null,
		'Doorvaartopening sluis': null,
		'Einde garantieperiode': null,
		Fundering: null,
		'Gewenst kwaliteitsniveau': null,
		Gewicht: null,
		Hoogte: null,
		'Hoogte nivelleerschijf': null,
		'Hoogte nivelleerschijf tov NAP': null,
		'ID uit oude beheerindeling': '680914',
		Installateur: null,
		'Jaar laatste conservering': null,
		'Jaar van aanleg': null,
		'Kerende hoogte': null,
		Kleur: null,
		Kunstwerkpositionering: null,
		Lengte: null,
		Leverancier: null,
		Levensduur: null,
		Looprichel: null,
		Materiaal: null,
		Memo: null,
		Monumentnummer: null,
		'NEN Conditiescore': null,
		'NEN Verzorgingsscore': null,
		Onderhoudsplichtige: null,
		Onderhoudsregime: null,
		Opleverdatum: null,
		Code: 'BRU0238-115-1',
		Renovatiejaar: null,
		Reservedeuren: null,
		Risiconiveau: null,
		Risicowaarde: null,
		'Technische levensduur': null,
		'Theoretisch eindjaar': null,
		'Type deurbediening': null,
		'Type monument': null,
		'Type nivelleerschijf': null,
		Vervangingsfactor: null,
		Vervangingsjaar: null,
		'Vervangingsjaar recent': null,
		Vervangingswaarde: null,
		Verwijderdatum: null,
		Discipline: null,
		Installatie: null,
		Deelinstallatie: null,
		GUID: '{20272A18-8546-41B5-AF93-2A9B2955FA7E}',
		Id: 653399,
		Description: null,
		IMGeoId: null,
		Valid_Till: null,
		LastUpdate: '2019-12-06T13:24:56',
		Revisie: 1,
	},
};

export const gisibElement2: GisibFeature<GisibElement> = {
	type: 'Feature',
	geometry: {
		type: '',
		crs: null,
		coordinates: [[[]]],
	},
	properties: {
		'NEN Type element': {
			Id: 2224,
			GUID: '{A3F6B9BF-71DE-43C4-9D34-E0965ECA7202}',
			Url: '/api/Collections/NEN Type element/items/2224',
			Description: 'Basculekelder',
		},
		Hoeveelheid: null,
		Eenheid: null,
		Specificatie: null,
		'NEN Conditiescore opname': null,
		'NEN Conditiescore opname_DATE': null,
		'NEN Verzorgingsscore opname': null,
		'NEN Verzorgingsscore opname_DATE': null,
		'Civiele constructie': {
			Id: 651385,
			GUID: '',
			Url: '/api/Collections/Civiele constructie/items/651385',
			Description: null,
		},
		'NEN Code': null,
		'Type sluisdeur': null,
		'Aangemaakt door': 'Reitsma, Tjitse',
		Aanleghoogte: null,
		'Anti graffiti voorziening': null,
		'Begin garantieperiode': null,
		Bouwjaar: null,
		Breedte: null,
		'Breedte nivelleerschijf': null,
		Deurnummer: null,
		Deursetnummer: null,
		Diepte: null,
		Dikte: null,
		'Doorvaartopening sluis': null,
		'Einde garantieperiode': null,
		Fundering: null,
		'Gewenst kwaliteitsniveau': null,
		Gewicht: null,
		Hoogte: null,
		'Hoogte nivelleerschijf': null,
		'Hoogte nivelleerschijf tov NAP': null,
		'ID uit oude beheerindeling': '674631',
		Installateur: null,
		'Jaar laatste conservering': null,
		'Jaar van aanleg': null,
		'Kerende hoogte': null,
		Kleur: null,
		Kunstwerkpositionering: null,
		Lengte: null,
		Leverancier: null,
		Levensduur: null,
		Looprichel: null,
		Materiaal: null,
		Memo: null,
		Monumentnummer: null,
		'NEN Conditiescore': null,
		'NEN Verzorgingsscore': null,
		Onderhoudsplichtige: null,
		Onderhoudsregime: null,
		Opleverdatum: null,
		Code: 'BRU0238-247-1',
		Renovatiejaar: null,
		Reservedeuren: null,
		Risiconiveau: null,
		Risicowaarde: null,
		'Technische levensduur': null,
		'Theoretisch eindjaar': null,
		'Type deurbediening': null,
		'Type monument': null,
		'Type nivelleerschijf': null,
		Vervangingsfactor: null,
		Vervangingsjaar: null,
		'Vervangingsjaar recent': null,
		Vervangingswaarde: null,
		Verwijderdatum: null,
		Discipline: null,
		Installatie: null,
		Deelinstallatie: null,
		GUID: '{B6D3584D-4FF0-47E0-B403-20076998BD43}',
		Id: 653400,
		Description: null,
		IMGeoId: null,
		Valid_Till: null,
		LastUpdate: '2019-12-06T13:24:56',
		Revisie: 1,
	},
};
