import { GisibUnit } from '../types/GisibUnit';
import { GisibFeature } from '../types/GisibFeature';

export const gisibUnit1: GisibFeature<GisibUnit> = {
	type: 'Feature',
	geometry: {
		type: 'Polygon',
		crs: null,
		coordinates: [[[]]],
	},
	properties: {
		'NEN Element': {
			Id: 654250,
			GUID: '{6169745D-1A02-402E-B1C9-F33ABB9D7D24}',
			Url: '/api/Collections/NEN Element/items/654250',
			Description: null,
		},
		Hoeveelheid: 1450,
		Specificatie: null,
		'Jaar van aanleg': null,
		'Jaar uitgevoerd onderhoud': null,
		'Jaar laatste conservering': null,
		Kleur: null,
		'BGT Bronhouder': null,
		'BGT Eindregistratie': null,
		'BGT Type': null,
		'BGT In onderzoek': null,
		'BGT Objecttype': null,
		'BGT Opmerking': null,
		'BGT Status': null,
		'ID uit oude beheerindeling': '685500',
		Identificatie: null,
		'LV publicatiedatum': null,
		'Relatieve hoogteligging': null,
		'Tijdstip registratie': null,
		Beweegbaar: null,
		'Hoort bij type overbrugging': null,
		'Type overbruggingsdeel': null,
		'NEN Type bouwdeel': {
			Id: 2554,
			GUID: '{DDAB4AC2-2616-44B9-97BB-57A78A243D02}',
			Url: '/api/Collections/NEN Type bouwdeel/items/2554',
			Description: 'Langsligger',
		},
		'NEN Conditiescore opname': '1',
		'NEN Conditiescore opname_DATE': '2020-12-31T00:00:00',
		'NEN Verzorgingsscore opname': '1',
		'NEN Verzorgingsscore opname_DATE': '2020-12-31T00:00:00',
		Conservering: null,
		Ingrijpmoment: null,
		Kunstwerkpositionering: null,
		Kwaliteitsnota: null,
		Levensduur: null,
		Memo: null,
		'NEN Conditiescore berekend': null,
		'NEN Conditiescore vastgesteld': null,
		'NEN Eenheid': null,
		'NEN Vakdiscipline': {
			Id: 3264,
			GUID: '{8D340D4C-57A3-4165-B018-E50E8465B67F}',
			Url: '/api/Collections/NEN Vakdiscipline/items/3264',
			Description: 'Kunstwerken',
		},
		'NEN Verzorgingsscore vastgesteld': null,
		Onderhoudsstrategie: null,
		'Reserveonderdeel aanwezig': false,
		Risiconiveau: null,
		Risicowaarde: null,
		'Totale hoeveelheid': null,
		Vervangingsfactor: null,
		Vervangingsjaar: null,
		'Vervangingsjaar recent': null,
		Vervangingswaarde: null,
		'Aangemaakt door': 'Ligthart, Adrie ',
		'IMGeo Plusstatus': null,
		'BOR Type': null,
		'IMGeo Plustype': null,
		Eenheid: 'm',
		Deelsportcomplex: null,
		Inwinningsbedrijf: null,
		Sportterrein: null,
		Sportveld: null,
		Discipline: null,
		Locatieaanduiding: null,
		'TAG Nummer': null,
		Sectie: null,
		Revisietekeningnummer: null,
		Fabrikant: null,
		Model: null,
		Installateur: null,
		Installatiedatum: null,
		'Datum tekening gewijzigd': null,
		Serienummer: null,
		'NEN Materiaalsoort': {
			Id: 3165,
			GUID: '{1079DC19-DFC5-45A7-B8CB-478AF3B9BCB7}',
			Url: '/api/Collections/NEN Materiaalsoort/items/3165',
			Description: 'Staal',
		},
		'Civiele constructie': {
			Id: 651378,
			GUID: '',
			Url: '/api/Collections/Civiele constructie/items/651378',
			Description: null,
		},
		Code: 'BRU0231-147-1328',
		GUID: '{926901BA-C69D-4CF6-AAB1-4C1D82C78C87}',
		Id: 661837,
		Description: null,
		IMGeoId: null,
		Valid_Till: null,
		LastUpdate: '2021-06-21T09:25:26.849313',
		Revisie: 2,
	},
};

export const gisibUnit2: GisibFeature<GisibUnit> = {
	type: 'Feature',
	geometry: {
		type: 'Polygon',
		crs: null,
		coordinates: [[[]]],
	},
	properties: {
		'NEN Element': {
			Id: 660068,
			GUID: '{85B61BEE-F4B5-401B-8221-FCF2626FABC9}',
			Url: '/api/Collections/NEN Element/items/660068',
			Description: null,
		},
		Hoeveelheid: 176,
		Specificatie: '-',
		'Jaar van aanleg': null,
		'Jaar uitgevoerd onderhoud': null,
		'Jaar laatste conservering': null,
		Kleur: null,
		'BGT Bronhouder': null,
		'BGT Eindregistratie': null,
		'BGT Type': null,
		'BGT In onderzoek': null,
		'BGT Objecttype': null,
		'BGT Opmerking': null,
		'BGT Status': null,
		'ID uit oude beheerindeling': '682751',
		Identificatie: null,
		'LV publicatiedatum': null,
		'Relatieve hoogteligging': null,
		'Tijdstip registratie': null,
		Beweegbaar: null,
		'Hoort bij type overbrugging': null,
		'Type overbruggingsdeel': null,
		'NEN Type bouwdeel': {
			Id: 2741,
			GUID: '{71454A8E-4EB5-4A0E-9F36-9383832E79BF}',
			Url: '/api/Collections/NEN Type bouwdeel/items/2741',
			Description: 'Wand',
		},
		'NEN Conditiescore opname': '1',
		'NEN Conditiescore opname_DATE': '2020-12-31T00:00:00',
		'NEN Verzorgingsscore opname': '1',
		'NEN Verzorgingsscore opname_DATE': '2020-12-31T00:00:00',
		Conservering: null,
		Ingrijpmoment: null,
		Kunstwerkpositionering: null,
		Kwaliteitsnota: null,
		Levensduur: null,
		Memo: null,
		'NEN Conditiescore berekend': null,
		'NEN Conditiescore vastgesteld': null,
		'NEN Eenheid': null,
		'NEN Vakdiscipline': {
			Id: 3264,
			GUID: '{8D340D4C-57A3-4165-B018-E50E8465B67F}',
			Url: '/api/Collections/NEN Vakdiscipline/items/3264',
			Description: 'Kunstwerken',
		},
		'NEN Verzorgingsscore vastgesteld': null,
		Onderhoudsstrategie: null,
		'Reserveonderdeel aanwezig': false,
		Risiconiveau: null,
		Risicowaarde: null,
		'Totale hoeveelheid': null,
		Vervangingsfactor: null,
		Vervangingsjaar: null,
		'Vervangingsjaar recent': null,
		Vervangingswaarde: null,
		'Aangemaakt door': 'Devente-Prins, Ellen',
		'IMGeo Plusstatus': null,
		'BOR Type': null,
		'IMGeo Plustype': null,
		Eenheid: 'm2',
		Deelsportcomplex: null,
		Inwinningsbedrijf: null,
		Sportterrein: null,
		Sportveld: null,
		Discipline: null,
		Locatieaanduiding: null,
		'TAG Nummer': null,
		Sectie: null,
		Revisietekeningnummer: null,
		Fabrikant: null,
		Model: null,
		Installateur: null,
		Installatiedatum: null,
		'Datum tekening gewijzigd': null,
		Serienummer: null,
		'NEN Materiaalsoort': {
			Id: 3156,
			GUID: '{08037948-D160-4B3E-87D5-0B5BE66ACF39}',
			Url: '/api/Collections/NEN Materiaalsoort/items/3156',
			Description: 'Steen',
		},
		'Civiele constructie': {
			Id: 651238,
			GUID: '',
			Url: '/api/Collections/Civiele constructie/items/651238',
			Description: null,
		},
		Code: 'BRU0082-202-1619',
		GUID: '{7D53C2B8-52C2-49E2-8CDB-E0E38A5729D9}',
		Id: 661643,
		Description: null,
		IMGeoId: null,
		Valid_Till: null,
		LastUpdate: '2021-06-21T09:25:31.708657',
		Revisie: 2,
	},
};
