import { MJOPRecord } from '../types/mjop-record';

export const mjopRecordMock: MJOPRecord = {
	asset: {
		code: '',
		assetName: '',
		marineInfrastrutureType: '',
		mainMaterial: '',
		surveys: [
			{
				condition: '',
				careScore: '0',
				elements: [],
				craInspectionScore: 0,
			},
		],
	},
	survey: {
		condition: '',
		careScore: '0',
		elements: [],
		craInspectionScore: 0,
	},
	careScore: '',
	code: '',
	assetName: '',
	marineInfrastrutureType: '',
	mainMaterial: '',
	condition: '',
	careCondition: '',
	elementName: '',
	unitName: '',
	unitMaterial: '',
	quantity: 0,
	quantityUnitOfMeasurement: '',
	failureModeName: '',
	faaloorzaak: '',
	bronVanFalen: '',
	gevolgVanFalen: '',
	analysisRemarks: '',
	verificationRemarks: '',
	maintenanceRemarks: '',
	verificationRamsR: '',
	verificationRamsA: '',
	verificationRamsS: '',
	verificationRamsC: '',
	verificationRamsEc: '',
	verificationRamsEnv: '',
	verificationRamsP: '',
	verificationRamsWeightedPriority: '',
	craInspectionScore: '',
	defectName: '',
	seriousness: 0,
	intensity: 0,
	extend: 0,
	repairAdvice: '',
	defectScore: 0,
	defectCareScore: 0,
	ramsR: '',
	ramsA: '',
	ramsS: '',
	ramsEc: '',
	ramsEnv: '',
	ramsWeightedPriority: '',
	ramsTotalPriority: '',
	unitCondition: '',
	elementCondition: '',
	unitCare: '',
	elementCare: '',
	maintenanceDescription: '',
	maintenanceType: '',
	maintenanceCycle: '',
	maintenanceUnitPrice: '',
	maintenanceCostSurcharge: '',
	totalCost: '',
	totalCostWithSurcharge: '',
	maintenanceYear: '',
	cyclicMaintenance: {},
};
