export const infrastrutureTypeList = [
	{ value: '1', text: 'Beschoeiing' },
	{ value: '2', text: 'Beweegbare brug' },
	{ value: '3', text: 'Damwand' },
	{ value: '4', text: 'Duiker' },
	{ value: '5', text: 'Duikerbrug' },
	{ value: '6', text: 'Fiets-voetbrug' },
	{ value: '7', text: 'Geluidsmuur' },
	{ value: '8', text: 'Glooiing' },
	{ value: '9', text: 'Keermuur' },
	{ value: '10', text: 'Loswal' },
	{ value: '11', text: 'Meerpaal' },
	{ value: '12', text: 'Meerstoel' },
	{ value: '13', text: 'Natuurlijke oever' },
	{ value: '14', text: 'Perkoenpalen' },
	{ value: '15', text: 'Overkluizing' },
	{ value: '16', text: 'Schanskorf' },
	{ value: '17', text: 'Keersluis' },
	{ value: '18', text: 'Schutsluis' },
	{ value: '19', text: 'Spoorbrug' },
	{ value: '20', text: 'Steiger' },
	{ value: '21', text: 'Stuw' },
	{ value: '22', text: 'Trap' },
	{ value: '23', text: 'Trambrug' },
	{ value: '24', text: 'Tunnel' },
	{ value: '25', text: 'Verkeersbrug' },
	{ value: '26', text: 'Viaduct' },
	{ value: '27', text: 'Vlonder' },
	{ value: '28', text: 'Walmuur' },
];
