/**
 * This file is auto-generated using the `npm run generate:gisib-api-types` command.
 * DO NOT EDIT or risk that your changes will be overwritten.
 */
export type GisibAsset = {
	GUID: string;
	'NEN Conditiescore opname': null | string;
	'NEN Conditiescore opname_DATE': null | string;
	'NEN Verzorgingsscore opname': null | string;
	'NEN Verzorgingsscore opname_DATE': null | string;
	'Type gedetailleerd'?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Aangemaakt door': null | string;
	Aanleghoogte: null | string;
	Beheerder?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Beheerder gedetailleerd'?: {
		Id: null | number;
		GUID: null | string;
		Url: null | string;
		Description: null | string;
	};
	Beheergebied?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Beschermde flora en fauna': null | string;
	'BGT Bronhouder': null | string;
	'BGT Eindregistratie': null | string;
	'BGT In onderzoek': null | string;
	'BGT Objecttype': null | string;
	'BGT Opmerking': null | string;
	'BGT Status': null | string;
	Breedte: null | string;
	Eigenaar?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Eigenaar gedetailleerd'?: {
		Id: null | number;
		GUID: null | string;
		Url: null | string;
		Description: null | string;
	};
	Gebiedstype: null | string;
	Gebruiksfunctie: null | string;
	Gemeente?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Grondsoort: null | string;
	Hoogte: null | string;
	'ID uit oude beheerindeling': null | string;
	Identificatie: null | string;
	'IMGeo Plusstatus': null | string;
	'Jaar uitgevoerd onderhoud': null | string;
	'Jaar van aanleg': null | number;
	Lengte: null | string;
	Leverancier: null | string;
	Ligging: null | string;
	'LV publicatiedatum': null | string;
	Materiaal?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Memo: null | string;
	MSLINK: null | string;
	Objecttype?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Onderhoudsplichtige: null | string;
	'Openbare ruimte': null | string;
	Opleverdatum: null | string;
	Oppervlakte: null | string;
	'Relatieve hoogteligging': null | string;
	'Theoretisch eindjaar': null | string;
	'Tijdstip registratie': null | string;
	Type?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Verwijderdatum: null | string;
	Waterschap: null | string;
	Wijk?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Wijze van inwinning': null | string;
	Woonplaats?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Zettingsgevoeligheid: null | string;
	Objectnaam: null | string;
	Objectnummer: null | string;
	'NEN Type beheerobject'?: {
		Id: null | number;
		GUID: null | string;
		Url: null | string;
		Description: null | string;
	};
	Postcode: null | string;
	'Stadsdeel of kern'?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Zettingsgevoeligheid gedetailleerd': null | string;
	Buurt?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	'Grondsoort gedetailleerd': null | string;
	'Datum inwinning': null | string;
	Vervangingsjaar: null | string;
	Code: null | string;
	Vervangingswaarde: null | string;
	Wegnummer: null | string;
	'Actueel kwaliteitsniveau': null | string;
	'BGT Type': null | string;
	Fabrikant: null | string;
	Fundering: null | string;
	'Gewenst kwaliteitsniveau': null | string;
	'IMGeo Plustype': null | string;
	Installateur: null | string;
	Kleur: null | string;
	Locatieaanduiding: null | string;
	'Type onderdeel': null | string;
	'BOR Type': null | string;
	Conditiescore: null | string;
	Beheerafspraak?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
	Deelsportcomplex: null | string;
	Inwinningsbedrijf: null | string;
	Sportterrein: null | string;
	Sportveld: null | string;
	Rangvolgorde: null | string;
	Id: number;
	Description: null | string;
	IMGeoId: null | string;
	Valid_Till: null | string;
	LastUpdate: string;
	Revisie: number;
	Status?: { Id: null | number; GUID: null | string; Url: null | string; Description: null | string };
};
