/**
 * This file is auto-generated using the `npm run generate:gisib-api-types` command.
 * DO NOT EDIT or risk that your changes will be overwritten.
 */
export type GisibElement = {
	'NEN Type element': { Id: number; GUID: string; Url: string; Description: string };
	Hoeveelheid: null | string;
	Eenheid: null | string;
	Specificatie: null | string;
	'NEN Conditiescore opname': null | string;
	'NEN Conditiescore opname_DATE': null | string;
	'NEN Verzorgingsscore opname': null | string;
	'NEN Verzorgingsscore opname_DATE': null | string;
	'Civiele constructie': { Id: number; GUID: string; Url: string; Description: null | string };
	'NEN Code': null | string;
	'Type sluisdeur': null | string;
	'Aangemaakt door': string;
	Aanleghoogte: null | string;
	'Anti graffiti voorziening': null | string;
	'Begin garantieperiode': null | string;
	Bouwjaar: null | string;
	Breedte: null | string;
	'Breedte nivelleerschijf': null | string;
	Deurnummer: null | string;
	Deursetnummer: null | string;
	Diepte: null | string;
	Dikte: null | string;
	'Doorvaartopening sluis': null | string;
	'Einde garantieperiode': null | string;
	Fundering: null | string;
	'Gewenst kwaliteitsniveau': null | string;
	Gewicht: null | string;
	Hoogte: null | string;
	'Hoogte nivelleerschijf': null | string;
	'Hoogte nivelleerschijf tov NAP': null | string;
	'ID uit oude beheerindeling': string;
	Installateur: null | string;
	'Jaar laatste conservering': null | string;
	'Jaar van aanleg': null | number;
	'Kerende hoogte': null | string;
	Kleur: null | string;
	Kunstwerkpositionering: null | string;
	Lengte: null | string;
	Leverancier: null | string;
	Levensduur: null | string;
	Looprichel: null | string;
	Materiaal: null | string;
	Memo: null | string;
	Monumentnummer: null | string;
	'NEN Conditiescore': null | string;
	'NEN Verzorgingsscore': null | string;
	Onderhoudsplichtige: null | string;
	Onderhoudsregime: null | string;
	Opleverdatum: null | string;
	Code: string;
	Renovatiejaar: null | string;
	Reservedeuren: null | string;
	Risiconiveau: null | string;
	Risicowaarde: null | string;
	'Technische levensduur': null | string;
	'Theoretisch eindjaar': null | string;
	'Type deurbediening': null | string;
	'Type monument': null | string;
	'Type nivelleerschijf': null | string;
	Vervangingsfactor: null | string;
	Vervangingsjaar: null | string;
	'Vervangingsjaar recent': null | string;
	Vervangingswaarde: null | string;
	Verwijderdatum: null | string;
	Discipline: null | string;
	Installatie: null | string;
	Deelinstallatie: null | string;
	GUID: string;
	Id: number;
	Description: null | string;
	IMGeoId: null | string;
	Valid_Till: null | string;
	LastUpdate: string;
	Revisie: number;
};
