/**
 * This file is auto-generated using the `npm run generate:gisib-api-types` command.
 * DO NOT EDIT or risk that your changes will be overwritten.
 */
export type GisibUnit = {
	'NEN Element': { Id: number; GUID: string; Url: string; Description: null | string };
	Hoeveelheid: number | null;
	Specificatie: null | string;
	'Jaar van aanleg': null | string;
	'Jaar uitgevoerd onderhoud': null | string;
	'Jaar laatste conservering': null | string;
	Kleur: null | string;
	'BGT Bronhouder': null | string;
	'BGT Eindregistratie': null | string;
	'BGT Type': null | string;
	'BGT In onderzoek': null | string;
	'BGT Objecttype': null | string;
	'BGT Opmerking': null | string;
	'BGT Status': null | string;
	'ID uit oude beheerindeling': string;
	Identificatie: null | string;
	'LV publicatiedatum': null | string;
	'Relatieve hoogteligging': null | string;
	'Tijdstip registratie': null | string;
	Beweegbaar: null | string;
	'Hoort bij type overbrugging': null | string;
	'Type overbruggingsdeel': null | string;
	'NEN Type bouwdeel': { Id: number; GUID: string; Url: string; Description: string };
	'NEN Conditiescore opname': string | null;
	'NEN Conditiescore opname_DATE': string | null;
	'NEN Verzorgingsscore opname': string | null;
	'NEN Verzorgingsscore opname_DATE': string | null;
	Conservering: null | string;
	Ingrijpmoment: null | string;
	Kunstwerkpositionering: null | string;
	Kwaliteitsnota: null | string;
	Levensduur: null | string;
	Memo: null | string;
	'NEN Conditiescore berekend': null | string;
	'NEN Conditiescore vastgesteld': null | string;
	'NEN Eenheid': null | string;
	'NEN Vakdiscipline': { Id: number; GUID: string; Url: string; Description: string };
	'NEN Verzorgingsscore vastgesteld': null | string;
	Onderhoudsstrategie: null | string;
	'Reserveonderdeel aanwezig': boolean;
	Risiconiveau: null | string;
	Risicowaarde: null | string;
	'Totale hoeveelheid': null | string;
	Vervangingsfactor: null | string;
	Vervangingsjaar: null | string;
	'Vervangingsjaar recent': null | string;
	Vervangingswaarde: null | string;
	'Aangemaakt door': string;
	'IMGeo Plusstatus': null | string;
	'BOR Type': null | string;
	'IMGeo Plustype': null | string;
	Eenheid: string | null;
	Deelsportcomplex: null | string;
	Inwinningsbedrijf: null | string;
	Sportterrein: null | string;
	Sportveld: null | string;
	Discipline: null | string;
	Locatieaanduiding: null | string;
	'TAG Nummer': null | string;
	Sectie: null | string;
	Revisietekeningnummer: null | string;
	Fabrikant: null | string;
	Model: null | string;
	Installateur: null | string;
	Installatiedatum: null | string;
	'Datum tekening gewijzigd': null | string;
	Serienummer: null | string;
	'NEN Materiaalsoort': { Id: number; GUID: string; Url: string; Description: string };
	'Civiele constructie': { Id: number; GUID: string; Url: string; Description: null | string };
	Code: string;
	GUID: string;
	Id: number;
	Description: null | string;
	IMGeoId: null | string;
	Valid_Till: null | string;
	LastUpdate: string;
	Revisie: number;
};
