export type GisibUnit = {
	type: string;
	geometry: {
		type: string;
		crs: undefined;
		coordinates: [[[]]];
	};
	properties: {
		'NEN Element': {
			Id: number;
			GUID: string;
			Url: string;
			Description: undefined;
		};
		Hoeveelheid: undefined;
		Specificatie: undefined;
		'Jaar van aanleg': undefined;
		'Jaar uitgevoerd onderhoud': undefined;
		'Jaar laatste conservering': undefined;
		Kleur: undefined;
		'BGT Bronhouder': undefined;
		'BGT Eindregistratie': undefined;
		'BGT Type': undefined;
		'BGT In onderzoek': undefined;
		'BGT Objecttype': undefined;
		'BGT Opmerking': undefined;
		'BGT Status': undefined;
		'ID uit oude beheerindeling': string;
		Identificatie: undefined;
		'LV publicatiedatum': undefined;
		'Relatieve hoogteligging': undefined;
		'Tijdstip registratie': undefined;
		Beweegbaar: undefined;
		'Hoort bij type overbrugging': undefined;
		'Type overbruggingsdeel': undefined;
		'NEN Type bouwdeel': {
			Id: number;
			GUID: string;
			Url: string;
			Description: string;
		};
		'NEN Conditiescore opname': undefined;
		'NEN Conditiescore opname_DATE': undefined;
		'NEN Verzorgingsscore opname': undefined;
		'NEN Verzorgingsscore opname_DATE': undefined;
		Conservering: undefined;
		Ingrijpmoment: undefined;
		Kunstwerkpositionering: undefined;
		Kwaliteitsnota: undefined;
		Levensduur: undefined;
		Memo: undefined;
		'NEN Conditiescore berekend': undefined;
		'NEN Conditiescore vastgesteld': undefined;
		'NEN Eenheid': undefined;
		'NEN Vakdiscipline': {
			Id: number;
			GUID: string;
			Url: string;
			Description: string;
		};
		'NEN Verzorgingsscore vastgesteld': undefined;
		Onderhoudsstrategie: undefined;
		'Reserveonderdeel aanwezig': boolean;
		Risiconiveau: undefined;
		Risicowaarde: undefined;
		'Totale hoeveelheid': undefined;
		Vervangingsfactor: undefined;
		Vervangingsjaar: undefined;
		'Vervangingsjaar recent': undefined;
		Vervangingswaarde: undefined;
		'Aangemaakt door': 'Devente-Prins, Ellen';
		'IMGeo Plusstatus': undefined;
		'BOR Type': undefined;
		'IMGeo Plustype': undefined;
		Eenheid: undefined;
		Deelsportcomplex: undefined;
		Inwinningsbedrijf: undefined;
		Sportterrein: undefined;
		Sportveld: undefined;
		Discipline: undefined;
		Locatieaanduiding: undefined;
		'TAG Nummer': undefined;
		Sectie: undefined;
		Revisietekeningnummer: undefined;
		Fabrikant: undefined;
		Model: undefined;
		Installateur: undefined;
		Installatiedatum: undefined;
		'Datum tekening gewijzigd': undefined;
		Serienummer: undefined;
		'NEN Materiaalsoort': {
			Id: number;
			GUID: string;
			Url: string;
			Description: string;
		};
		'Civiele constructie': {
			Id: number;
			GUID: string;
			Url: string;
			Description: undefined;
		};
		Code: string;
		GUID: string;
		Id: number;
		Description: undefined;
		IMGeoId: undefined;
		Valid_Till: undefined;
		LastUpdate: string;
		Revisie: number;
	};
};
