export type GisibAsset = {
	type: string;
	geometry: {
		type: string;
		crs: string;
		coordinates: [[[]]];
	};
	properties: {
		GUID: undefined;
		'NEN Conditiescore opname': undefined;
		'NEN Conditiescore opname_DATE': undefined;
		'NEN Verzorgingsscore opname': undefined;
		'NEN Verzorgingsscore opname_DATE': undefined;
		'Type gedetailleerd': undefined;
		'Aangemaakt door': undefined;
		Aanleghoogte: undefined;
		Beheerder: undefined;
		'Beheerder gedetailleerd': undefined;
		Beheergebied: undefined;
		'Beschermde flora en fauna': undefined;
		'BGT Bronhouder': undefined;
		'BGT Eindregistratie': undefined;
		'BGT In onderzoek': undefined;
		'BGT Objecttype': undefined;
		'BGT Opmerking': undefined;
		'BGT Status': undefined;
		Breedte: undefined;
		Eigenaar: undefined;
		'Eigenaar gedetailleerd': undefined;
		Gebiedstype: undefined;
		Gebruiksfunctie: undefined;
		Gemeente: undefined;
		Grondsoort: undefined;
		Hoogte: undefined;
		'ID uit oude beheerindeling': undefined;
		Identificatie: undefined;
		'IMGeo Plusstatus': undefined;
		'Jaar uitgevoerd onderhoud': undefined;
		'Jaar van aanleg': undefined;
		Lengte: undefined;
		Leverancier: undefined;
		Ligging: undefined;
		'LV publicatiedatum': undefined;
		Materiaal: undefined;
		Memo: undefined;
		MSLINK: undefined;
		Objecttype: undefined;
		Onderhoudsplichtige: undefined;
		'Openbare ruimte': undefined;
		Opleverdatum: undefined;
		Oppervlakte: undefined;
		'Relatieve hoogteligging': undefined;
		'Theoretisch eindjaar': undefined;
		'Tijdstip registratie': undefined;
		Type: undefined;
		Verwijderdatum: undefined;
		Waterschap: undefined;
		Wijk: undefined;
		'Wijze van inwinning': undefined;
		Woonplaats: undefined;
		Zettingsgevoeligheid: undefined;
		Objectnaam: undefined;
		Objectnummer: string;
		'NEN Type beheerobject': undefined;
		Postcode: undefined;
		'Stadsdeel of kern': undefined;
		'Zettingsgevoeligheid gedetailleerd': undefined;
		Buurt: undefined;
		'Grondsoort gedetailleerd': undefined;
		'Datum inwinning': undefined;
		Vervangingsjaar: undefined;
		Code: undefined;
		Vervangingswaarde: undefined;
		Wegnummer: number | null;
		'Actueel kwaliteitsniveau': undefined;
		'BGT Type': undefined;
		Fabrikant: undefined;
		Fundering: undefined;
		'Gewenst kwaliteitsniveau': undefined;
		'IMGeo Plustype': undefined;
		Installateur: undefined;
		Kleur: undefined;
		Locatieaanduiding: undefined;
		'Type onderdeel': undefined;
		'BOR Type': undefined;
		Conditiescore: undefined;
		Beheerafspraak: {
			Id: number;
			GUID: string;
			Url: string;
			Description: string;
		};
		Deelsportcomplex: undefined;
		Inwinningsbedrijf: undefined;
		Sportterrein: undefined;
		Sportveld: undefined;
		Rangvolgorde: undefined;
		Id: number;
		Description: undefined;
		IMGeoId: undefined;
		Valid_Till: undefined;
		LastUpdate: string;
		Revisie: number;
	};
};
